
before_script:
  - mkdir bin
  - export PATH=$PATH:$PWD/bin
  - curl -sLO https://storage.googleapis.com/git-repo-downloads/repo
  - mv repo bin
  - chmod +x bin/repo
  - repo init -u git://github.com/couchbase/manifest.git -m branch-master.xml
  - repo sync
  - make
