sudo: required

os:
  - linux
#  - osx

# no speedup from caching $HOME/.cbdepscache

language: c

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./setup_linux.sh          ; fi

before_script:
  # set up custom bin dir
  - mkdir bin
  - export PATH=$PATH:$PWD/bin
  - curl -sL -o bin/repo https://storage.googleapis.com/git-repo-downloads/repo
  - chmod +x bin/repo
  # set up git
  - git config --global user.email "marty.schoch@gmail.com"
  - git config --global user.name "Marty Couchbase Developer Edition Schoch"
  - git config --global color.ui false
  # run repo
  - repo init -u git://github.com/couchbase/manifest.git -m branch-master.xml
  - repo sync

script:
  - make
