sudo: required

language: c

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:george-edison55/precise-backports
 - sudo apt-get update -qq
 - sudo apt-get install g++-4.8 libsnappy-dev zlib1g-dev libbz2-dev cmake-data cmake -qq
 - export CXX="g++-4.8" CC="gcc-4.8"

before_script:
  # set up custom bin dir
  - mkdir bin
  - export PATH=$PATH:$PWD/bin
  - curl -sL -o bin/repo https://storage.googleapis.com/git-repo-downloads/repo
  - chmod +x bin/repo
  # set up git
  - git config --global user.email "marty.schoch@gmail.com"
  - git config --global user.name "Marty Couchbase Developer Edition Schoch"
  - git config --global color.ui false
  # run repo
  - repo init -u git://github.com/couchbase/manifest.git -m branch-master.xml
  - repo sync
  - make
